### ISSUE TITLE
TODO for angular conversion

### ISSUE THREAD

**Issue by zackarychapple** [angular-ui/ui-calendar#138]
- [ ] removal of jQuery dependency
- [ ] removal of jQuery-ui dependency
- [ ] removal fullCalendar.js dependency 
- [ ] removal fullCalendar.css dependency 
- [ ] css to SCSS
- [ ] convert gcal plugin
